name: repo-activity-check

on:
  schedule:
    - cron: "0 23 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check-activity
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "\nPublic repositories:"
          gh search repos --owner=cicsdev --visibility=public --archived=false --limit=99 --json=name --jq=.[].name | sort | tee public-repos.txt
          echo "\nActive repositories:"
          gh search repos --owner=cicsdev --visibility=public --archived=false --limit=99 --updated=">2022-11-28" --json=name --jq=.[].name | sort | tee active-repos.txt
          echo "\nStale repositories:"
          comm -13 active-repos.txt public-repos.txt | tee stale-repos.txt
          count=$(wc -l < stale-repos.txt)
          [ $count -eq 0 ] || { echo "::error title=Stale repositories::There are $count stale repositories"; exit 1; }
